name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore src/Natadon.DataAccess.SqlServer.csproj
    - name: Build
      run: dotnet build src/Natadon.DataAccess.SqlServer.csproj --configuration Release --no-restore
    - name: Publish DataAccess.SqlServer
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/Natadon.DataAccess.SqlServer.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
